# A4図面解析システム設定ファイル

# OpenAI API設定
openai:
  api_key: "your-openai-api-key-here"  # 実際のAPIキーに置き換えてください
  model: "gpt-4-vision-preview"
  max_tokens: 2000
  temperature: 0.1

# データベース設定
database:
  path: "database/drawing_analysis.db"
  backup_path: "database/backups/"
  auto_backup: true
  backup_interval_hours: 24

# ファイル設定
files:
  input_directory: "data/input/"
  output_directory: "data/output/"
  temp_directory: "data/temp/"
  samples_directory: "data/samples/"
  supported_formats: [".jpg", ".jpeg", ".png", ".pdf", ".tiff"]

# A4画像処理設定
image_processing:
  target_dpi: 300
  min_dpi: 150
  max_dpi: 600
  auto_enhance: true
  noise_reduction: true
  contrast_adjustment: true
  
# 処理設定
processing:
  batch_size: 10
  max_workers: 4
  timeout_seconds: 300
  retry_attempts: 3

# 抽出設定
extraction:
  confidence_threshold: 0.7
  auto_correction: true
  default_fields:
    - "部品番号"
    - "製品名"
    - "材質"
    - "寸法"
    - "重量"
    - "表面処理"
    - "精度"
    - "図面番号"

# エクセル設定
excel:
  template_directory: "data/excel_templates/"
  output_directory: "data/excel_output/"
  default_template: "default_template.xlsx"

# 学習設定
learning:
  auto_learning: true
  confidence_threshold: 0.8
  similarity_threshold: 0.85
  min_training_samples: 5
  template_creation_threshold: 0.9

# UI設定
ui:
  page_title: "A4図面解析システム"
  theme: "light"
  sidebar_state: "expanded"
  show_tips: true

# ログ設定
logging:
  level: "INFO"
  file: "logs/drawing_analysis.log"
  max_size_mb: 100
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# 通知設定（オプション）
notifications:
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: ""
    password: ""
    recipients: []

# システム監視設定
monitoring:
  enable_metrics: true
  health_check_interval: 300
  disk_space_threshold: 85
  memory_threshold: 80